// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/lb_agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBindingRequest) Reset() {
	*x = AddBindingRequest{}
	mi := &file_proto_lb_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBindingRequest) ProtoMessage() {}

func (x *AddBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lb_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBindingRequest.ProtoReflect.Descriptor instead.
func (*AddBindingRequest) Descriptor() ([]byte, []int) {
	return file_proto_lb_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AddBindingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddBindingRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddBindingRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type DeleteBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindingRequest) Reset() {
	*x = DeleteBindingRequest{}
	mi := &file_proto_lb_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindingRequest) ProtoMessage() {}

func (x *DeleteBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lb_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBindingRequest) Descriptor() ([]byte, []int) {
	return file_proto_lb_agent_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteBindingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddBackendServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBackendServerRequest) Reset() {
	*x = AddBackendServerRequest{}
	mi := &file_proto_lb_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBackendServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBackendServerRequest) ProtoMessage() {}

func (x *AddBackendServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lb_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBackendServerRequest.ProtoReflect.Descriptor instead.
func (*AddBackendServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lb_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AddBackendServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddBackendServerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddBackendServerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type DeleteBackendServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackendServerRequest) Reset() {
	*x = DeleteBackendServerRequest{}
	mi := &file_proto_lb_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackendServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackendServerRequest) ProtoMessage() {}

func (x *DeleteBackendServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lb_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackendServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackendServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lb_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBackendServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GenericReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericReply) Reset() {
	*x = GenericReply{}
	mi := &file_proto_lb_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericReply) ProtoMessage() {}

func (x *GenericReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lb_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericReply.ProtoReflect.Descriptor instead.
func (*GenericReply) Descriptor() ([]byte, []int) {
	return file_proto_lb_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GenericReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SocksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SocksByState  []*SocksByState        `protobuf:"bytes,1,rep,name=socksByState,proto3" json:"socksByState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocksReply) Reset() {
	*x = SocksReply{}
	mi := &file_proto_lb_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocksReply) ProtoMessage() {}

func (x *SocksReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lb_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocksReply.ProtoReflect.Descriptor instead.
func (*SocksReply) Descriptor() ([]byte, []int) {
	return file_proto_lb_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SocksReply) GetSocksByState() []*SocksByState {
	if x != nil {
		return x.SocksByState
	}
	return nil
}

type SocksByState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Socks         []*Sock                `protobuf:"bytes,2,rep,name=socks,proto3" json:"socks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocksByState) Reset() {
	*x = SocksByState{}
	mi := &file_proto_lb_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocksByState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocksByState) ProtoMessage() {}

func (x *SocksByState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lb_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocksByState.ProtoReflect.Descriptor instead.
func (*SocksByState) Descriptor() ([]byte, []int) {
	return file_proto_lb_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SocksByState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SocksByState) GetSocks() []*Sock {
	if x != nil {
		return x.Socks
	}
	return nil
}

type Sock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          uint32                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,2,opt,name=localAddr,proto3" json:"localAddr,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sock) Reset() {
	*x = Sock{}
	mi := &file_proto_lb_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sock) ProtoMessage() {}

func (x *Sock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lb_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sock.ProtoReflect.Descriptor instead.
func (*Sock) Descriptor() ([]byte, []int) {
	return file_proto_lb_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Sock) GetUuid() uint32 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *Sock) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *Sock) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

var File_proto_lb_agent_proto protoreflect.FileDescriptor

const file_proto_lb_agent_proto_rawDesc = "" +
	"\n" +
	"\x14proto/lb_agent.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"U\n" +
	"\x11AddBindingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"*\n" +
	"\x14DeleteBindingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"[\n" +
	"\x17AddBackendServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"0\n" +
	"\x1aDeleteBackendServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\fGenericReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\n" +
	"SocksReply\x127\n" +
	"\fsocksByState\x18\x01 \x03(\v2\x13.proto.SocksByStateR\fsocksByState\"G\n" +
	"\fSocksByState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12!\n" +
	"\x05socks\x18\x02 \x03(\v2\v.proto.SockR\x05socks\"X\n" +
	"\x04Sock\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\rR\x04uuid\x12\x1c\n" +
	"\tlocalAddr\x18\x02 \x01(\tR\tlocalAddr\x12\x1e\n" +
	"\n" +
	"remoteAddr\x18\x03 \x01(\tR\n" +
	"remoteAddr2\xe4\x02\n" +
	"\x11LoadBalancerAgent\x12;\n" +
	"\n" +
	"AddBinding\x12\x18.proto.AddBindingRequest\x1a\x13.proto.GenericReply\x12A\n" +
	"\rDeleteBinding\x12\x1b.proto.DeleteBindingRequest\x1a\x13.proto.GenericReply\x12G\n" +
	"\x10AddBackendServer\x12\x1e.proto.AddBackendServerRequest\x1a\x13.proto.GenericReply\x12M\n" +
	"\x13DeleteBackendServer\x12!.proto.DeleteBackendServerRequest\x1a\x13.proto.GenericReply\x127\n" +
	"\n" +
	"TrackSocks\x12\x16.google.protobuf.Empty\x1a\x11.proto.SocksReplyB\tZ\a.;protob\x06proto3"

var (
	file_proto_lb_agent_proto_rawDescOnce sync.Once
	file_proto_lb_agent_proto_rawDescData []byte
)

func file_proto_lb_agent_proto_rawDescGZIP() []byte {
	file_proto_lb_agent_proto_rawDescOnce.Do(func() {
		file_proto_lb_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lb_agent_proto_rawDesc), len(file_proto_lb_agent_proto_rawDesc)))
	})
	return file_proto_lb_agent_proto_rawDescData
}

var file_proto_lb_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_lb_agent_proto_goTypes = []any{
	(*AddBindingRequest)(nil),          // 0: proto.AddBindingRequest
	(*DeleteBindingRequest)(nil),       // 1: proto.DeleteBindingRequest
	(*AddBackendServerRequest)(nil),    // 2: proto.AddBackendServerRequest
	(*DeleteBackendServerRequest)(nil), // 3: proto.DeleteBackendServerRequest
	(*GenericReply)(nil),               // 4: proto.GenericReply
	(*SocksReply)(nil),                 // 5: proto.SocksReply
	(*SocksByState)(nil),               // 6: proto.SocksByState
	(*Sock)(nil),                       // 7: proto.Sock
	(*emptypb.Empty)(nil),              // 8: google.protobuf.Empty
}
var file_proto_lb_agent_proto_depIdxs = []int32{
	6, // 0: proto.SocksReply.socksByState:type_name -> proto.SocksByState
	7, // 1: proto.SocksByState.socks:type_name -> proto.Sock
	0, // 2: proto.LoadBalancerAgent.AddBinding:input_type -> proto.AddBindingRequest
	1, // 3: proto.LoadBalancerAgent.DeleteBinding:input_type -> proto.DeleteBindingRequest
	2, // 4: proto.LoadBalancerAgent.AddBackendServer:input_type -> proto.AddBackendServerRequest
	3, // 5: proto.LoadBalancerAgent.DeleteBackendServer:input_type -> proto.DeleteBackendServerRequest
	8, // 6: proto.LoadBalancerAgent.TrackSocks:input_type -> google.protobuf.Empty
	4, // 7: proto.LoadBalancerAgent.AddBinding:output_type -> proto.GenericReply
	4, // 8: proto.LoadBalancerAgent.DeleteBinding:output_type -> proto.GenericReply
	4, // 9: proto.LoadBalancerAgent.AddBackendServer:output_type -> proto.GenericReply
	4, // 10: proto.LoadBalancerAgent.DeleteBackendServer:output_type -> proto.GenericReply
	5, // 11: proto.LoadBalancerAgent.TrackSocks:output_type -> proto.SocksReply
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_lb_agent_proto_init() }
func file_proto_lb_agent_proto_init() {
	if File_proto_lb_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lb_agent_proto_rawDesc), len(file_proto_lb_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lb_agent_proto_goTypes,
		DependencyIndexes: file_proto_lb_agent_proto_depIdxs,
		MessageInfos:      file_proto_lb_agent_proto_msgTypes,
	}.Build()
	File_proto_lb_agent_proto = out.File
	file_proto_lb_agent_proto_goTypes = nil
	file_proto_lb_agent_proto_depIdxs = nil
}
